- lib/alerts/alerts_pub_sub.ex
- test/alerts/alerts_pub_sub_test.exs
We don't want to broadcast all alerts with every change.
> fix: Broadcast only the changed data

- lib/alerts.ex
- lib/alerts/alerts_pub_sub.ex
- lib/alerts_viewer_web.ex
- lib/alerts_viewer_web/components/core_components.ex
- lib/alerts_viewer_web/live/alert_component.ex
- lib/alerts_viewer_web/live/alerts_live.ex
- lib/alerts_viewer_web/live/alerts_live.html.heex
- lib/alerts_viewer_web/router.ex
- lib/alerts_viewer_web/string_helpers.ex
- test/alerts/alerts_pub_sub_test.exs
- test/alerts_test.exs
- test/alerts_viewer_web/live/alerts_live_test.exs
- test/alerts_viewer_web/string_helpers_test.exs
Display raw informed entity data for now.
Also:
- feat: Get an alert
- style: Use the header component
- style: Remove padding on the select component
Options with long names were overlapping with the disclosure triangle.
> feat: Show a single alert with details

- README.md
No ticket, I just noticed that this was missing while walking through the codebase.
> docs: Link to the architecture doc from the readme

- lib/alerts/alert.ex
- lib/alerts/parser.ex
It was missing, but now, it's here
🚦
> Adds SIGNAL_ISSUE as cause in alerts parser

- lib/alerts.ex
- lib/alerts_viewer_web/live/bus_live.ex
- lib/alerts_viewer_web/live/bus_live.html.heex
- test/alerts_test.exs
Displays actual alerts' severity and age. Adds a function to Alerts to arrange alerts data to make it easier to parse.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204597186510077
> Show alert severity and age

- ARCHITECTURE.md
- config/config.exs
- env.example
- lib/alerts_viewer/application.ex
- lib/alerts_viewer_web/live/bus_live.ex
- lib/alerts_viewer_web/live/bus_live.html.heex
- lib/trip_updates/gtfs_supervisor.ex
- lib/trip_updates/parser/gtfs_realtime_enhanced.ex
- lib/trip_updates/stop_time_update.ex
- lib/trip_updates/supervisor.ex
- lib/trip_updates/trip.ex
- lib/trip_updates/trip_update.ex
- lib/trip_updates/trip_updates.ex
- lib/trip_updates/trip_updates_pub_sub.ex
- test/alerts_viewer_web/live/bus_live_test.exs
- test/support/fixtures/trip_updates_enhanced.json
- test/trip_updates/gtfs_supervisor_test.exs
- test/trip_updates/parser/gtfs_realtime_enhanced_test.exs
- test/trip_updates/supervisor_test.exs
- test/trip_updates/trip_updates_pub_sub_test.exs
- test/trip_updates/trip_updates_test.exs
Asana task: https://app.asana.com/0/1167196461144361/1204597186510078/f
Adds trip updates GTFS data source. Adds pubsub for same to get list of routes with block waivers. Adds to frontend.
> Block Waivers from Trip Updates

- lib/alerts_viewer_web/components/core_components.ex
- lib/alerts_viewer_web/date_time_helpers.ex
Displays all times in Eastern standard time. This affects everything that uses the date_time core component.
Asana Task: None, sorry, this was small so I just sorta did it.
> Display times in EST

- lib/alerts_viewer_web/live/bus_live.ex
We were displaying all kinds of alerts, this restricts to just alerts with an effect of "delay".
Asana task: https://app.asana.com/0/1167196461144361/1204992413147837/f
> Only show "delay" type alerts on bus page

- config/config.exs
- lib/alerts_viewer_web/live/delay_alert_algorithm/base_algorithm_components/one_slider_component.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/max_adherence_component.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/max_instantaneous_minus_scheduled_headway_component.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/median_adherence_component.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/median_and_standard_deviation_component_adherence.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/median_instantaneous_headway_component.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/median_instantaneous_minus_scheduled_headway_component.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/standard_deviation_adherence_component.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/standard_deviation_instantaneous_headway_component.ex
- lib/alerts_viewer_web/live/delay_alert_algorithm/standard_deviation_instantaneous_minus_scheduled_headway_component.ex
- lib/routes/route_stats.ex
- test/routes/route_stats_test.exs
Asana ticket: [Bus delay algorithms: peak/max values of adherence and/or headways](https://app.asana.com/0/1204819229687089/1205010427056660)
2 new components:
- MaxAdherenceComponent
- MaxInstantaneousMinusScheduledHeadwayComponent
Also, an initial refactor: OneSliderComponent allows any slider values
This means that the snapshot function is currently duplicated in every
component, but I'm putting that off for the moment because I think we
might end up changing how that works when we build out data logging.
(I.e., I'm wondering if snapshots will go away to be replaced by logging.)
> feat: Max value bus delay algorithms for adherence and headway

- .github/workflows/create-asana-attachment.yaml
This will attach GitHub PR links to our Asana tickets.
Ironically, no Asana ticket for this. We have this set up in https://github.com/mbta/alerts_concierge but I realized not here yet.
> ci: Create Asana Attachment GitHub action

- lib/alerts/alert.ex
- lib/alerts_viewer_web/date_time_helpers.ex
- lib/alerts_viewer_web/live/alerts_to_close_live.html.heex
- lib/alerts_viewer_web/live/bus_live.html.heex
- test/alerts/alert_test.exs
One tiny step towards [Tweak /open-delay-alerts columns and styling](https://app.asana.com/0/1167196461144361/1205250462129251). I started playing with it just for fun but figured it didn't hurt to throw it in.
Round down to the nearest hour or minute.
> feature: Display alert durations in friendly hours or minutes

- bin/splunk-csv-to-json
No Asana task.
Our "snapshot" data is saved in Splunk as JSON, but in plaintext lines that also contain other data. This prevents us from exporting just the snapshot data lines. This script allows us to export these log lines from Splunk as a CSV file, and then running this strips the extra bits and formats the results as proper JSON.
> feat: Script to convert Splunk CSV exports into JSON

- lib/alerts/alert.ex
- lib/alerts_viewer_web/live/alerts_to_close_live.ex
- lib/alerts_viewer_web/live/alerts_to_close_live.html.heex
- lib/alerts_viewer_web/live/stop_recommendation_algorithm/adherence_component.ex
- lib/alerts_viewer_web/live/stop_recommendation_algorithm/alert_duration_component.ex
- lib/alerts_viewer_web/live/stop_recommendation_algorithm/base_algorithm_components/one_slider_component.ex
- lib/alerts_viewer_web/live/stop_recommendation_algorithm/headway_deviation_component.ex
- lib/alerts_viewer_web/live/stop_recommendation_algorithm/median_adherence_component.ex
- lib/alerts_viewer_web/live/stop_recommendation_algorithm/median_headway_deviation_diff_component.ex
- lib/routes.ex
Rows are now by alert, not route.
Routes without names are filtered out from display. Stats columns with multiple routes display comma-separated, route closures and dropped trips will show if any route on the alert qualifies. Aside from combined routes, alerts with multiple routes appear to be an edge case.
I also had to do a bit of refactoring since we don't need to arrange the page around a keyword list anymore.
Asana task: https://app.asana.com/0/1167196461144361/1205250462129249/f
> Rearranges alerts_to_close_page

- lib/alerts_viewer_web/components/core_components.ex
I noticed that we were using heroicons but none of them were showing up. Upon further investigations, the function we were using to show them requires a plugin to be added to the tailwind config file, and the individual svgs to be added to the asset folder (the plugin not being defined was why these were just kind of failing silently). Additionally we were importing the elixir [Heroicons library](https://hexdocs.pm/heroicons/Heroicons.html) but not using it. I switched all instances of icons over to using Heroicons library functions and deleted the old import code.
We were really only using them in a few places, but now we can add heroicons icons to our heart's content.
No ticket, this is more of a bugfix
Before:
After:
> Use heroicons library functions

- livebooks/bus_route_alert_regression.livemd
No Asana ticket.
Explore bus route snapshot data downloaded from Splunk and use it to train a logistic regression model.
Tweaking the model params (the best ones are saved here) and running with 10,529 data points (split 80/20 between training and testing) from evening rush hour one day and morning rush hour the next day, the best results I got were:
Accuracy: 81%
F-measure: 89%
Recall: 22%
Precision: 57%
> feat: Bus route alert regression ML Livebook

- assets/js/app.js
- lib/alerts_viewer_web/components/core_components.ex
- lib/alerts_viewer_web/live/alerts_to_close_live.ex
- lib/alerts_viewer_web/live/alerts_to_close_live.html.heex
- lib/alerts_viewer_web/live/open_delay_alerts_live.html.heex
Changes to "Alerts to Close" page:
- number of columns reduced
- title 'tooltip' added to Peak Deviation column header
- rows without recommended alerts are muted
- wording change on dropped trip
- dropped trip icon changed to circle with minus sign
- alert ids can be copied to clipboard
- Adherence called median instead of average
Also contains a few small fixes I missed in the last PR.
Asana ticket: https://app.asana.com/0/1167196461144361/1205250462129251/f
and also https://app.asana.com/0/1167196461144361/1205250462129252/f
> Various Stylings

- lib/alerts_viewer_web/live/alerts_to_close_live.ex
- test/alerts_viewer_web/live/alerts_to_close_live_test.exs
Now handles Alerts on which all Routes have no headway data, does not recommend them for closure.
No ticket; bugfix
> no closure recommended if no headways on routes

- env.example
- lib/trip_updates/parser/gtfs_realtime_enhanced.ex
This was throwing an occasional error, at least locally, so I put in a nil check.
Also updated .env.example to have an example URL that doesn't rely on AWS auth.
No card; bugfix
> Added nil check in Trip Update Parser

- lib/trip_updates/trip_updates_pub_sub.ex
- test/trip_updates/trip_updates_pub_sub_test.exs
- test/trip_updates/trip_updates_test.exs
It was handling StopTimeUpdate arrivals as if they were datetimes, but they're unix timestamps.
No card, bugfix
> Stop time update arrivals are in unix time

- lib/alerts_viewer_web/components/core_components.ex
- lib/alerts_viewer_web/live/alerts_to_close_live.html.heex
- lib/trip_updates/trip_updates_pub_sub.ex
- test/trip_updates/trip_updates_pub_sub_test.exs
- test/trip_updates/trip_updates_test.exs
Looks at the schedule_relationship in the trip instead of stop update reason to detect dropped trips.
Also added some centering to the table, and the dropped trip icon is now dim if the row isn't a suggested closure.
Asana ticket: https://app.asana.com/0/1167196461144361/1205354484020913/f
> Use schedule relationship to detect dropped trip

- config/config.exs
- config/test.exs
- lib/alerts_viewer_web/components/layouts/app.html.heex
- lib/alerts_viewer_web/controllers/page_html/home.html.heex
- lib/alerts_viewer_web/live/put_flags_in_assigns_hook.ex
- lib/alerts_viewer_web/put_flags_in_session_plug.ex
- lib/alerts_viewer_web/router.ex
- mix.exs
- mix.lock
- test/alerts_viewer_web/live/alerts_to_close_live_test.exs
- test/alerts_viewer_web/put_flags_in_session_plug_test.exs
Introduces the Laboratory library, and puts Alerts and Bus link behind a flag. They can be re-enabled by visiting the `/_flags` route and refreshing.
I had to add some extra things to get it to work. Laboratory works via cookies, which are only available on the `conn`. If the flag is "on", there is a cookie with the flag name set to "true". If it's "off", there is no cookie with that name at all. Only the root layout in LiveView can access the `conn` assign. The solution was to make a Plug that iterates through the flags set in config, checks the `conn` for their presence, and adds them to the `session` with a value of `true` if they're found and `false` if they're not.
Then, to make it so you don't have to worry about individually adding flags to session assigns, I added an `on_mount` …
> add laboratory library for flags, get it to work in liveview

- .tool-versions
- Dockerfile
- lib/routes.ex
- mix.exs
- test/snapshot_logger/snapshot_logger_test.exs
No Asana ticket. Erlang 25 is broken in Sonoma so I needed this upgrade in order to run the app.
- elixir 1.15.6-otp-26
- erlang 26.1.1
refactor: Use Logger.warning instead of warn
Logger.warn has been deprecated.
fix (test): Adjust test conditions to be less sensitive
[Successful deploy](https://github.com/mbta/alerts_viewer/actions/runs/6471321022/job/17569501550)
> deps: Update Erlang and Elixir to the latest versions

- .github/workflows/deploy-dev.yml
This PR updates the deploy workflow to use v2 of the shared `build-push-ecr` and `deploy-ecs` actions. These updated actions assume an IAM role instead of relying on long-lasting AWS keys for an IAM user
> Fix: Update GitHub actions to assume role

- config/config.exs
- lib/alerts_viewer/application.ex
- lib/alerts_viewer_web/components/layouts.ex
- lib/alerts_viewer_web/components/layouts/root.html.heex
Asana ticket: app portion of [Add Google analytics](https://app.asana.com/0/1204819229687089/1205784855883890)
This follows up on the [infrastructure update](https://github.com/mbta/devops/pull/1299).
Get the GTM ID from an environment variable.
Live now on [dev-orange](https://alerts-viewer-dev-orange.mbtace.com).
> feat: Add Google Tag Manager scripts for analytics

- .github/workflows/elixir.yml
CI runs are currently failing in the setup phase.
Update cache action from v2 to v4.
Update upload-artifact from v2 to v4.
> ci: Update workflow actions
