assets/tailwind.config.js
lib/alerts_viewer_web/components/core_components.ex
lib/alerts_viewer_web/live/alerts_live.html.heex

Use it to render the table of alerts.
style: Set a brand color
Matched a blue found on the mbta.com website.

feat: Create a live_table component

---

lib/alerts.ex
lib/alerts/alert.ex
lib/alerts/alerts_pub_sub.ex
lib/alerts_viewer_web/components/core_components.ex
lib/alerts_viewer_web/live/alerts_live.ex
lib/alerts_viewer_web/live/alerts_live.html.heex
lib/alerts_viewer_web/live/test_live.ex
test/alerts/alerts_pub_sub_test.exs
test/alerts_viewer_web/live/alerts_live_test.exs

Update pub-sub to broadcast all alerts with every update.
Use the standard table now that we don't need extra behaviors.

feat: Filter by effect

---

.tool-versions

Remove nodejs dependency we don't actually use

deps: Update elixir and erlang to latest versions

---

lib/alerts_viewer_web/controllers/health_controller.ex
lib/alerts_viewer_web/router.ex
test/alerts_viewer_web/controllers/health_controller_test.exs

Returns a 200 Ok response when the server is running.

feat: Health check route

---

lib/alerts_viewer_web/live/bus_live.ex
lib/alerts_viewer_web/live/bus_live.html.heex

For now just faking a suggested alert algorithm.

feat: Icons for suggested alerts and error types

---

ARCHITECTURE.md
README.md

Asana task: [🛠️ ARCHITECTURE.md file](https://app.asana.com/0/1167196461144361/1204603597646648)
Also, add a project description to the README.

docs: ARCHITECTURE.md file

---

.gitignore
README.md
env.example

Just adds some setup instructions, I cribbed most of it off alerts_concierge.

README update

---

lib/alerts_viewer_web/live/bus_live.ex
lib/alerts_viewer_web/live/bus_live.html.heex

Only affects display of values in live view

Displays individual, median, and standard deviation values in minutes

---

config/config.exs
lib/alerts_viewer_web/live/delay_alert_algorithm/median_and_standard_deviation_component.ex
lib/alerts_viewer_web/live/delay_alert_algorithm/standard_deviation_component.ex

Displays recommended alerts if the Median and Standard Deviation of adherence are above their respective set minimum values.
(also contains a couple small improvements to the standard deviation module)
card: https://app.asana.com/0/1167196461144361/1204603605299998/f

Standard Deviation and Median component

---

lib/alerts_viewer_web/live/bus_live.ex

I meant to put this in the last PR (as per your suggestion) but merged before I pushed it up.

Small refactor to minutes component

---

lib/alerts_viewer/application.ex
lib/alerts_viewer_web/live/delay_alert_algorithm/median_and_standard_deviation_component_adherence.ex
lib/snapshot_logger/snapshot_logger.ex
test/snapshot_logger/snapshot_logger_test.exs

Asana task: https://app.asana.com/0/1167196461144361/1205105472690153/f

Sends stats snapshot to Logger

---

lib/trip_updates/trip_updates_pub_sub.ex
test/trip_updates/trip_updates_pub_sub_test.exs

Also compares the datetimes correctly

Adds nil handling to alert filtering

---

config/config.exs
lib/alerts_viewer_web/live/bus_live.html.heex
lib/alerts_viewer_web/live/delay_alert_algorithm/max_headway_deviation_component.ex
lib/alerts_viewer_web/live/delay_alert_algorithm/median_headway_deviation_component.ex
lib/alerts_viewer_web/live/delay_alert_algorithm/standard_deviation_headway_deviation_component.ex
lib/alerts_viewer_web/live/stop_recommendation_algorithm/median_headway_deviation_diff_component.ex
lib/routes/route_stats.ex
test/routes/route_stats_test.exs
test/snapshot_logger/snapshot_logger_test.exs

Asana ticket: [Rename (instantaneous - scheduled) to headway deviation](https://app.asana.com/0/1204819229687089/1205119141073760)

feat: Rename (instantaneous - scheduled) to headway deviation

---

lib/snapshot_logger/snapshot_logger.ex

This ensures that data isn't truncated in Splunk. Include a timestamp in order to group complete sets of snapshots.

fix: Log bus route snapshots individually

---

lib/snapshot_logger/snapshot_logger.ex
test/snapshot_logger/snapshot_logger_test.exs

To prevent data from being truncated in Splunk.

fix: Log algorithm snapshots individually

---

lib/routes/route_stats.ex
lib/snapshot_logger/snapshot_logger.ex
test/routes/route_stats_test.exs

No Asana ticket, just 2 more data points that seemed like they could be useful.

feat: Log the max instantaneous headway and number of vehicles in our bus route snapshots

---

lib/alerts_viewer_web/live/alerts_to_close_live.html.heex

Asana task: https://app.asana.com/0/1167196461144361/1205271069999475/f

Small alerts close page tweaks

---

README.md

No card, just wanted to update the readme with information about Laboratory.

Updates the readme with info about flags

---

lib/alerts_viewer_web/live/alerts_to_close_live.ex
lib/alerts_viewer_web/live/alerts_to_close_live.html.heex

Asana ticket: https://app.asana.com/0/1167196461144361/1205500145817229/f
Adds severity column, removes adherence column, rearranges columns.

Alerts to Close page updates

---

lib/alerts_viewer_web/live/alerts_to_close_live.ex
lib/alerts_viewer_web/live/alerts_to_close_live.html.heex
lib/routes/route_stats.ex
lib/vehicles/vehicle.ex
test/routes/route_stats_pub_sub_test.exs
test/routes/route_stats_test.exs

Asana ticket: [Add vehicle number to table](https://app.asana.com/0/1204819229687089/1205586650983595)

feat: Show vehicle number with max headway deviation

---

CONTRIBUTORS.md

Asana ticket: [Add a CONTRIBUTORS.md file to alerts-viewer](https://app.asana.com/0/1167196461144361/1205837253862467)
We want to recognize the entire team, not just the engineers.

docs: List all of the contributors to this project

---

lib/alerts/parser.ex
test/alerts/parser_test.exs

Asana ticket: [AlertsUI Feed Not updating](https://app.asana.com/0/1204819229687089/1205984632669342)

fix: Correctly parse unknown Alerts causes
